server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  min-money: 0.1
  max-money: 9999
  description: the minimum amount is ${limit.min-money}, the max amount is ${limit.max-money}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/luckymoney
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
